import { Person } from "../types/generated";

export const PeopleArray: Person[] = [
  {
    id: "0001",
    name: "andrew",
    age: 24,
    job: "",
    favouriteRoute: "",
  },
  {
    id: "0002",
    name: "michael",
    age: 35,
    job: "",
    favouriteRoute: "Moss Traverse",
  },
  {
    id: "0003",
    name: "emma",
    age: 42,
    job: "Marketing Director",
    favouriteRoute: "",
  },
  {
    id: "0004",
    name: "james",
    age: 31,
    job: "Data Analyst",
    favouriteRoute: "",
  },
  {
    id: "0005",
    name: "olivia",
    age: 26,
    job: "UX Designer",
    favouriteRoute: "Pine Wall",
  },
  {
    id: "0006",
    name: "david",
    age: 39,
    job: "",
    favouriteRoute: "Summit Overhang",
  },
  {
    id: "0007",
    name: "sophia",
    age: 33,
    job: "HR Specialist",
    favouriteRoute: "",
  },
  {
    id: "0008",
    name: "daniel",
    age: 45,
    job: "Senior Architect",
    favouriteRoute: "Boulder Dream",
  },
  {
    id: "0009",
    name: "ava",
    age: 29,
    job: "DevOps Engineer",
    favouriteRoute: "Granite Start",
  },
  {
    id: "0010",
    name: "christopher",
    age: 37,
    job: "Finance Manager",
    favouriteRoute: "",
  },
  {
    id: "0011",
    name: "isabella",
    age: 30,
    job: "Content Writer",
    favouriteRoute: "Moss Traverse",
  },
  {
    id: "0012",
    name: "matthew",
    age: 44,
    job: "Operations Manager",
    favouriteRoute: "Pine Wall",
  },
  {
    id: "0013",
    name: "mia",
    age: 27,
    job: "Graphic Designer",
    favouriteRoute: "Sky Crack",
  },
  {
    id: "0014",
    name: "ethan",
    age: 38,
    job: "Business Analyst",
    favouriteRoute: "",
  },
  {
    id: "0015",
    name: "charlotte",
    age: 34,
    job: "Account Executive",
    favouriteRoute: "Summit Overhang",
  },
  {
    id: "0016",
    name: "ryan",
    age: 41,
    job: "IT Manager",
    favouriteRoute: "Boulder Dream",
  },
  {
    id: "0017",
    name: "amelia",
    age: 25,
    job: "Junior Developer",
    favouriteRoute: "",
  },
  {
    id: "0018",
    name: "benjamin",
    age: 36,
    job: "Project Coordinator",
    favouriteRoute: "Granite Start",
  },
  {
    id: "0019",
    name: "harper",
    age: 32,
    job: "Legal Counsel",
    favouriteRoute: "Moss Traverse",
  },
  {
    id: "0020",
    name: "alexander",
    age: 43,
    job: "Security Engineer",
    favouriteRoute: "",
  },
  {
    id: "0021",
    name: "ella",
    age: 29,
    job: "Customer Success Manager",
    favouriteRoute: "Pine Wall",
  },
  {
    id: "0022",
    name: "william",
    age: 40,
    job: "QA Lead",
    favouriteRoute: "Sky Crack",
  },
  {
    id: "0023",
    name: "lily",
    age: 31,
    job: "Brand Manager",
    favouriteRoute: "",
  },
  {
    id: "0024",
    name: "lucas",
    age: 37,
    job: "System Administrator",
    favouriteRoute: "Summit Overhang",
  },
  {
    id: "0025",
    name: "grace",
    age: 28,
    job: "Social Media Specialist",
    favouriteRoute: "Boulder Dream",
  },
];
